---
name: Test-Net-Connect
version: 0.01
author:
  - Nik Clayton <nik@FreeBSD.org>
abstract: Test::Builder based tests for network connectivity
license: bsd
requires:
  IO::Socket::INET: 0
  Net::DNS: 0
  Test::More: 0
provides:
  Test::Net::Connect:
    file: lib/Test/Net/Connect.pm
    version: 0.01
generated_by: Module::Build version 0.2611
